
package lifetime.authentication;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ApplicationManagementServiceSoap", targetNamespace = "http://LifeTimeServices/ApplicationManagementService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ApplicationManagementServiceSoap {


    /**
     * Returns a list of applications and their information, that are visible within the platform for the authenticated platform user.
     * 
     * @param status
     * @param authentication
     * @param applications
     * @param success
     */
    @WebMethod(operationName = "Application_List", action = "http://LifeTimeServices/ApplicationManagementService/Application_List")
    @RequestWrapper(localName = "Application_List", targetNamespace = "http://www.outsystems.com", className = "lifetime.authentication.ApplicationList")
    @ResponseWrapper(localName = "Application_ListResponse", targetNamespace = "http://www.outsystems.com", className = "lifetime.authentication.ApplicationListResponse")
    public void applicationList(
        @WebParam(name = "Authentication", targetNamespace = "http://www.outsystems.com")
        WebServiceSimpleAuthentication authentication,
        @WebParam(name = "Applications", targetNamespace = "http://www.outsystems.com", mode = WebParam.Mode.OUT)
        Holder<ArrayOfApplicationInfo> applications,
        @WebParam(name = "Status", targetNamespace = "http://www.outsystems.com", mode = WebParam.Mode.OUT)
        Holder<APIStatus> status,
        @WebParam(name = "Success", targetNamespace = "http://www.outsystems.com", mode = WebParam.Mode.OUT)
        Holder<Boolean> success);

    /**
     * Sets a tag for each application in a given environment.
     * 
     * @param status
     * @param environmentApplicationsForTag
     * @param authentication
     * @param success
     */
    @WebMethod(operationName = "Application_SetTag_Bulk", action = "http://LifeTimeServices/ApplicationManagementService/Application_SetTag_Bulk")
    @RequestWrapper(localName = "Application_SetTag_Bulk", targetNamespace = "http://www.outsystems.com", className = "lifetime.authentication.ApplicationSetTagBulk")
    @ResponseWrapper(localName = "Application_SetTag_BulkResponse", targetNamespace = "http://www.outsystems.com", className = "lifetime.authentication.ApplicationSetTagBulkResponse")
    public void applicationSetTagBulk(
        @WebParam(name = "Authentication", targetNamespace = "http://www.outsystems.com")
        WebServiceSimpleAuthentication authentication,
        @WebParam(name = "EnvironmentApplicationsForTag", targetNamespace = "http://www.outsystems.com")
        EnvironmentApplicationTagList environmentApplicationsForTag,
        @WebParam(name = "Status", targetNamespace = "http://www.outsystems.com", mode = WebParam.Mode.OUT)
        Holder<APIStatus> status,
        @WebParam(name = "Success", targetNamespace = "http://www.outsystems.com", mode = WebParam.Mode.OUT)
        Holder<Boolean> success);

    /**
     * Returns a solution binary file containing a set of applications given their versions.
     * 
     * @param applicationTagInfo
     * @param status
     * @param authentication
     * @param applicationSolutionBinary
     * @param solutionName
     * @param solutionDescription
     * @param environmentKey
     * @param success
     * @param applicationSolutionSize
     */
    @WebMethod(operationName = "Solution_PackAndDownload", action = "http://LifeTimeServices/ApplicationManagementService/Solution_PackAndDownload")
    @RequestWrapper(localName = "Solution_PackAndDownload", targetNamespace = "http://www.outsystems.com", className = "lifetime.authentication.SolutionPackAndDownload")
    @ResponseWrapper(localName = "Solution_PackAndDownloadResponse", targetNamespace = "http://www.outsystems.com", className = "lifetime.authentication.SolutionPackAndDownloadResponse")
    public void solutionPackAndDownload(
        @WebParam(name = "Authentication", targetNamespace = "http://www.outsystems.com")
        WebServiceSimpleAuthentication authentication,
        @WebParam(name = "EnvironmentKey", targetNamespace = "http://www.outsystems.com")
        String environmentKey,
        @WebParam(name = "ApplicationTagInfo", targetNamespace = "http://www.outsystems.com")
        ArrayOfApplicationTag applicationTagInfo,
        @WebParam(name = "SolutionName", targetNamespace = "http://www.outsystems.com")
        String solutionName,
        @WebParam(name = "SolutionDescription", targetNamespace = "http://www.outsystems.com")
        String solutionDescription,
        @WebParam(name = "Status", targetNamespace = "http://www.outsystems.com", mode = WebParam.Mode.OUT)
        Holder<APIStatus> status,
        @WebParam(name = "ApplicationSolutionBinary", targetNamespace = "http://www.outsystems.com", mode = WebParam.Mode.OUT)
        Holder<byte[]> applicationSolutionBinary,
        @WebParam(name = "ApplicationSolutionSize", targetNamespace = "http://www.outsystems.com", mode = WebParam.Mode.OUT)
        Holder<String> applicationSolutionSize,
        @WebParam(name = "Success", targetNamespace = "http://www.outsystems.com", mode = WebParam.Mode.OUT)
        Holder<Boolean> success);

    /**
     * The list of permission levels that a platform user has over an application.
     * 
     * @param status
     * @param authentication
     * @param applicationPermissionLevels
     * @param success
     */
    @WebMethod(operationName = "ApplicationPermissionLevel_List", action = "http://LifeTimeServices/ApplicationManagementService/ApplicationPermissionLevel_List")
    @RequestWrapper(localName = "ApplicationPermissionLevel_List", targetNamespace = "http://www.outsystems.com", className = "lifetime.authentication.ApplicationPermissionLevelList")
    @ResponseWrapper(localName = "ApplicationPermissionLevel_ListResponse", targetNamespace = "http://www.outsystems.com", className = "lifetime.authentication.ApplicationPermissionLevelListResponse")
    public void applicationPermissionLevelList(
        @WebParam(name = "Authentication", targetNamespace = "http://www.outsystems.com")
        WebServiceSimpleAuthentication authentication,
        @WebParam(name = "ApplicationPermissionLevels", targetNamespace = "http://www.outsystems.com", mode = WebParam.Mode.OUT)
        Holder<ArrayOfApplicationPermissionLevel> applicationPermissionLevels,
        @WebParam(name = "Status", targetNamespace = "http://www.outsystems.com", mode = WebParam.Mode.OUT)
        Holder<APIStatus> status,
        @WebParam(name = "Success", targetNamespace = "http://www.outsystems.com", mode = WebParam.Mode.OUT)
        Holder<Boolean> success);

}
