
package lifetime.authentication;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * The Platform API to acquire an authentication token to be used when invoking other Outsystems Platform APIs. After 5 minutes, the token expires.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AuthenticationService", targetNamespace = "http://LifeTimeServices/AuthenticationService/", wsdlLocation = "http://outsystemscloud/LifeTimeServices/AuthenticationService.asmx?WSDL")
public class AuthenticationService
    extends Service
{

    private final static URL AUTHENTICATIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(lifetime.authentication.AuthenticationService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = lifetime.authentication.AuthenticationService.class.getResource(".");
            url = new URL(baseUrl, "http://outsystemscloud/LifeTimeServices/AuthenticationService.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://outsystemscloud/LifeTimeServices/AuthenticationService.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        AUTHENTICATIONSERVICE_WSDL_LOCATION = url;
    }

    public AuthenticationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthenticationService() {
        super(AUTHENTICATIONSERVICE_WSDL_LOCATION, new QName("http://LifeTimeServices/AuthenticationService/", "AuthenticationService"));
    }

    /**
     * 
     * @return
     *     returns AuthenticationServiceSoap
     */
    @WebEndpoint(name = "AuthenticationServiceSoap")
    public AuthenticationServiceSoap getAuthenticationServiceSoap() {
        return super.getPort(new QName("http://LifeTimeServices/AuthenticationService/", "AuthenticationServiceSoap"), AuthenticationServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthenticationServiceSoap
     */
    @WebEndpoint(name = "AuthenticationServiceSoap")
    public AuthenticationServiceSoap getAuthenticationServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://LifeTimeServices/AuthenticationService/", "AuthenticationServiceSoap"), AuthenticationServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns AuthenticationServiceSoap
     */
    @WebEndpoint(name = "AuthenticationServiceSoap12")
    public AuthenticationServiceSoap getAuthenticationServiceSoap12() {
        return super.getPort(new QName("http://LifeTimeServices/AuthenticationService/", "AuthenticationServiceSoap12"), AuthenticationServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthenticationServiceSoap
     */
    @WebEndpoint(name = "AuthenticationServiceSoap12")
    public AuthenticationServiceSoap getAuthenticationServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://LifeTimeServices/AuthenticationService/", "AuthenticationServiceSoap12"), AuthenticationServiceSoap.class, features);
    }

}
