
package lifetime.authentication;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AuthenticationServiceSoap", targetNamespace = "http://LifeTimeServices/AuthenticationService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthenticationServiceSoap {


    /**
     * Returns an authentication token that is valid for 5 minutes.
     * 
     * @param username
     * @param status
     * @param token
     * @param success
     * @param password
     */
    @WebMethod(operationName = "Authentication_GetToken", action = "http://LifeTimeServices/AuthenticationService/Authentication_GetToken")
    @RequestWrapper(localName = "Authentication_GetToken", targetNamespace = "http://www.outsystems.com", className = "lifetime.authentication.AuthenticationGetToken")
    @ResponseWrapper(localName = "Authentication_GetTokenResponse", targetNamespace = "http://www.outsystems.com", className = "lifetime.authentication.AuthenticationGetTokenResponse")
    public void authenticationGetToken(
        @WebParam(name = "Username", targetNamespace = "http://www.outsystems.com")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://www.outsystems.com")
        String password,
        @WebParam(name = "Token", targetNamespace = "http://www.outsystems.com", mode = WebParam.Mode.OUT)
        Holder<String> token,
        @WebParam(name = "Status", targetNamespace = "http://www.outsystems.com", mode = WebParam.Mode.OUT)
        Holder<APIStatus> status,
        @WebParam(name = "Success", targetNamespace = "http://www.outsystems.com", mode = WebParam.Mode.OUT)
        Holder<Boolean> success);

}
