//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace LifetimeIntegration.LifetimeTeams {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TeamManagementServiceSoap", Namespace="http://LifeTimeServices/TeamManagementService/")]
    public partial class TeamManagementService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Team_CreateOrUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback Team_DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback Team_GetDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Team_RemoveApplicationOperationCompleted;
        
        private System.Threading.SendOrPostCallback Team_ListOperationCompleted;
        
        private System.Threading.SendOrPostCallback Team_AssignApplicationOperationCompleted;
        
        private System.Threading.SendOrPostCallback Team_RemoveUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback Team_AddUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TeamManagementService() {
            this.Url = global::LifetimeIntegration.Properties.Settings.Default.LifetimeIntegration_LifetimeTeams_TeamManagementService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Team_CreateOrUpdateCompletedEventHandler Team_CreateOrUpdateCompleted;
        
        /// <remarks/>
        public event Team_DeleteCompletedEventHandler Team_DeleteCompleted;
        
        /// <remarks/>
        public event Team_GetDetailsCompletedEventHandler Team_GetDetailsCompleted;
        
        /// <remarks/>
        public event Team_RemoveApplicationCompletedEventHandler Team_RemoveApplicationCompleted;
        
        /// <remarks/>
        public event Team_ListCompletedEventHandler Team_ListCompleted;
        
        /// <remarks/>
        public event Team_AssignApplicationCompletedEventHandler Team_AssignApplicationCompleted;
        
        /// <remarks/>
        public event Team_RemoveUserCompletedEventHandler Team_RemoveUserCompleted;
        
        /// <remarks/>
        public event Team_AddUserCompletedEventHandler Team_AddUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LifeTimeServices/TeamManagementService/Team_CreateOrUpdate", RequestNamespace="http://www.outsystems.com", ResponseNamespace="http://www.outsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Success")]
        public bool Team_CreateOrUpdate(WebServiceSimpleAuthentication Authentication, string TeamName, string Description, out APIStatus Status, out PlatformTeam PlatformTeam) {
            object[] results = this.Invoke("Team_CreateOrUpdate", new object[] {
                        Authentication,
                        TeamName,
                        Description});
            Status = ((APIStatus)(results[1]));
            PlatformTeam = ((PlatformTeam)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Team_CreateOrUpdateAsync(WebServiceSimpleAuthentication Authentication, string TeamName, string Description) {
            this.Team_CreateOrUpdateAsync(Authentication, TeamName, Description, null);
        }
        
        /// <remarks/>
        public void Team_CreateOrUpdateAsync(WebServiceSimpleAuthentication Authentication, string TeamName, string Description, object userState) {
            if ((this.Team_CreateOrUpdateOperationCompleted == null)) {
                this.Team_CreateOrUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTeam_CreateOrUpdateOperationCompleted);
            }
            this.InvokeAsync("Team_CreateOrUpdate", new object[] {
                        Authentication,
                        TeamName,
                        Description}, this.Team_CreateOrUpdateOperationCompleted, userState);
        }
        
        private void OnTeam_CreateOrUpdateOperationCompleted(object arg) {
            if ((this.Team_CreateOrUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Team_CreateOrUpdateCompleted(this, new Team_CreateOrUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LifeTimeServices/TeamManagementService/Team_Delete", RequestNamespace="http://www.outsystems.com", ResponseNamespace="http://www.outsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Success")]
        public bool Team_Delete(WebServiceSimpleAuthentication Authentication, string TeamName, out APIStatus Status) {
            object[] results = this.Invoke("Team_Delete", new object[] {
                        Authentication,
                        TeamName});
            Status = ((APIStatus)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Team_DeleteAsync(WebServiceSimpleAuthentication Authentication, string TeamName) {
            this.Team_DeleteAsync(Authentication, TeamName, null);
        }
        
        /// <remarks/>
        public void Team_DeleteAsync(WebServiceSimpleAuthentication Authentication, string TeamName, object userState) {
            if ((this.Team_DeleteOperationCompleted == null)) {
                this.Team_DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTeam_DeleteOperationCompleted);
            }
            this.InvokeAsync("Team_Delete", new object[] {
                        Authentication,
                        TeamName}, this.Team_DeleteOperationCompleted, userState);
        }
        
        private void OnTeam_DeleteOperationCompleted(object arg) {
            if ((this.Team_DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Team_DeleteCompleted(this, new Team_DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LifeTimeServices/TeamManagementService/Team_GetDetails", RequestNamespace="http://www.outsystems.com", ResponseNamespace="http://www.outsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Success")]
        public bool Team_GetDetails(WebServiceSimpleAuthentication Authentication, string TeamName, out APIStatus Status, out PlatformTeam PlatformTeam) {
            object[] results = this.Invoke("Team_GetDetails", new object[] {
                        Authentication,
                        TeamName});
            Status = ((APIStatus)(results[1]));
            PlatformTeam = ((PlatformTeam)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Team_GetDetailsAsync(WebServiceSimpleAuthentication Authentication, string TeamName) {
            this.Team_GetDetailsAsync(Authentication, TeamName, null);
        }
        
        /// <remarks/>
        public void Team_GetDetailsAsync(WebServiceSimpleAuthentication Authentication, string TeamName, object userState) {
            if ((this.Team_GetDetailsOperationCompleted == null)) {
                this.Team_GetDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTeam_GetDetailsOperationCompleted);
            }
            this.InvokeAsync("Team_GetDetails", new object[] {
                        Authentication,
                        TeamName}, this.Team_GetDetailsOperationCompleted, userState);
        }
        
        private void OnTeam_GetDetailsOperationCompleted(object arg) {
            if ((this.Team_GetDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Team_GetDetailsCompleted(this, new Team_GetDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LifeTimeServices/TeamManagementService/Team_RemoveApplication", RequestNamespace="http://www.outsystems.com", ResponseNamespace="http://www.outsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Success")]
        public bool Team_RemoveApplication(WebServiceSimpleAuthentication Authentication, string TeamName, string ApplicationKey, out APIStatus Status) {
            object[] results = this.Invoke("Team_RemoveApplication", new object[] {
                        Authentication,
                        TeamName,
                        ApplicationKey});
            Status = ((APIStatus)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Team_RemoveApplicationAsync(WebServiceSimpleAuthentication Authentication, string TeamName, string ApplicationKey) {
            this.Team_RemoveApplicationAsync(Authentication, TeamName, ApplicationKey, null);
        }
        
        /// <remarks/>
        public void Team_RemoveApplicationAsync(WebServiceSimpleAuthentication Authentication, string TeamName, string ApplicationKey, object userState) {
            if ((this.Team_RemoveApplicationOperationCompleted == null)) {
                this.Team_RemoveApplicationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTeam_RemoveApplicationOperationCompleted);
            }
            this.InvokeAsync("Team_RemoveApplication", new object[] {
                        Authentication,
                        TeamName,
                        ApplicationKey}, this.Team_RemoveApplicationOperationCompleted, userState);
        }
        
        private void OnTeam_RemoveApplicationOperationCompleted(object arg) {
            if ((this.Team_RemoveApplicationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Team_RemoveApplicationCompleted(this, new Team_RemoveApplicationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LifeTimeServices/TeamManagementService/Team_List", RequestNamespace="http://www.outsystems.com", ResponseNamespace="http://www.outsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Success")]
        public bool Team_List(WebServiceSimpleAuthentication Authentication, out APIStatus Status, out PlatformTeam[] PlatformTeams) {
            object[] results = this.Invoke("Team_List", new object[] {
                        Authentication});
            Status = ((APIStatus)(results[1]));
            PlatformTeams = ((PlatformTeam[])(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Team_ListAsync(WebServiceSimpleAuthentication Authentication) {
            this.Team_ListAsync(Authentication, null);
        }
        
        /// <remarks/>
        public void Team_ListAsync(WebServiceSimpleAuthentication Authentication, object userState) {
            if ((this.Team_ListOperationCompleted == null)) {
                this.Team_ListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTeam_ListOperationCompleted);
            }
            this.InvokeAsync("Team_List", new object[] {
                        Authentication}, this.Team_ListOperationCompleted, userState);
        }
        
        private void OnTeam_ListOperationCompleted(object arg) {
            if ((this.Team_ListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Team_ListCompleted(this, new Team_ListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LifeTimeServices/TeamManagementService/Team_AssignApplication", RequestNamespace="http://www.outsystems.com", ResponseNamespace="http://www.outsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Success")]
        public bool Team_AssignApplication(WebServiceSimpleAuthentication Authentication, string TeamName, string ApplicationKey, out APIStatus Status) {
            object[] results = this.Invoke("Team_AssignApplication", new object[] {
                        Authentication,
                        TeamName,
                        ApplicationKey});
            Status = ((APIStatus)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Team_AssignApplicationAsync(WebServiceSimpleAuthentication Authentication, string TeamName, string ApplicationKey) {
            this.Team_AssignApplicationAsync(Authentication, TeamName, ApplicationKey, null);
        }
        
        /// <remarks/>
        public void Team_AssignApplicationAsync(WebServiceSimpleAuthentication Authentication, string TeamName, string ApplicationKey, object userState) {
            if ((this.Team_AssignApplicationOperationCompleted == null)) {
                this.Team_AssignApplicationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTeam_AssignApplicationOperationCompleted);
            }
            this.InvokeAsync("Team_AssignApplication", new object[] {
                        Authentication,
                        TeamName,
                        ApplicationKey}, this.Team_AssignApplicationOperationCompleted, userState);
        }
        
        private void OnTeam_AssignApplicationOperationCompleted(object arg) {
            if ((this.Team_AssignApplicationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Team_AssignApplicationCompleted(this, new Team_AssignApplicationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LifeTimeServices/TeamManagementService/Team_RemoveUser", RequestNamespace="http://www.outsystems.com", ResponseNamespace="http://www.outsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Success")]
        public bool Team_RemoveUser(WebServiceSimpleAuthentication Authentication, string TeamName, string Username, out APIStatus Status) {
            object[] results = this.Invoke("Team_RemoveUser", new object[] {
                        Authentication,
                        TeamName,
                        Username});
            Status = ((APIStatus)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Team_RemoveUserAsync(WebServiceSimpleAuthentication Authentication, string TeamName, string Username) {
            this.Team_RemoveUserAsync(Authentication, TeamName, Username, null);
        }
        
        /// <remarks/>
        public void Team_RemoveUserAsync(WebServiceSimpleAuthentication Authentication, string TeamName, string Username, object userState) {
            if ((this.Team_RemoveUserOperationCompleted == null)) {
                this.Team_RemoveUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTeam_RemoveUserOperationCompleted);
            }
            this.InvokeAsync("Team_RemoveUser", new object[] {
                        Authentication,
                        TeamName,
                        Username}, this.Team_RemoveUserOperationCompleted, userState);
        }
        
        private void OnTeam_RemoveUserOperationCompleted(object arg) {
            if ((this.Team_RemoveUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Team_RemoveUserCompleted(this, new Team_RemoveUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LifeTimeServices/TeamManagementService/Team_AddUser", RequestNamespace="http://www.outsystems.com", ResponseNamespace="http://www.outsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Success")]
        public bool Team_AddUser(WebServiceSimpleAuthentication Authentication, string TeamName, string Username, string RoleName, out APIStatus Status) {
            object[] results = this.Invoke("Team_AddUser", new object[] {
                        Authentication,
                        TeamName,
                        Username,
                        RoleName});
            Status = ((APIStatus)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Team_AddUserAsync(WebServiceSimpleAuthentication Authentication, string TeamName, string Username, string RoleName) {
            this.Team_AddUserAsync(Authentication, TeamName, Username, RoleName, null);
        }
        
        /// <remarks/>
        public void Team_AddUserAsync(WebServiceSimpleAuthentication Authentication, string TeamName, string Username, string RoleName, object userState) {
            if ((this.Team_AddUserOperationCompleted == null)) {
                this.Team_AddUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTeam_AddUserOperationCompleted);
            }
            this.InvokeAsync("Team_AddUser", new object[] {
                        Authentication,
                        TeamName,
                        Username,
                        RoleName}, this.Team_AddUserOperationCompleted, userState);
        }
        
        private void OnTeam_AddUserOperationCompleted(object arg) {
            if ((this.Team_AddUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Team_AddUserCompleted(this, new Team_AddUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.outsystems.com")]
    public partial class WebServiceSimpleAuthentication {
        
        private string usernameField;
        
        private string passwordField;
        
        private string tokenField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.outsystems.com")]
    public partial class PlatformUser {
        
        private int idField;
        
        private string usernameField;
        
        private string nameField;
        
        private string emailField;
        
        private string roleNameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string RoleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.outsystems.com")]
    public partial class ApplicationShortInfo {
        
        private string nameField;
        
        private string keyField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.outsystems.com")]
    public partial class PlatformTeam {
        
        private int idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private ApplicationShortInfo[] applicationListField;
        
        private PlatformUser[] userListField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public ApplicationShortInfo[] ApplicationList {
            get {
                return this.applicationListField;
            }
            set {
                this.applicationListField = value;
            }
        }
        
        /// <remarks/>
        public PlatformUser[] UserList {
            get {
                return this.userListField;
            }
            set {
                this.userListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.outsystems.com")]
    public partial class APIStatus {
        
        private int idField;
        
        private int responseIdField;
        
        private string responseMessageField;
        
        private string responseAdditionalInfoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ResponseId {
            get {
                return this.responseIdField;
            }
            set {
                this.responseIdField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseAdditionalInfo {
            get {
                return this.responseAdditionalInfoField;
            }
            set {
                this.responseAdditionalInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void Team_CreateOrUpdateCompletedEventHandler(object sender, Team_CreateOrUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Team_CreateOrUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Team_CreateOrUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public APIStatus Status {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIStatus)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public PlatformTeam PlatformTeam {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PlatformTeam)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void Team_DeleteCompletedEventHandler(object sender, Team_DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Team_DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Team_DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public APIStatus Status {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIStatus)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void Team_GetDetailsCompletedEventHandler(object sender, Team_GetDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Team_GetDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Team_GetDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public APIStatus Status {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIStatus)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public PlatformTeam PlatformTeam {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PlatformTeam)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void Team_RemoveApplicationCompletedEventHandler(object sender, Team_RemoveApplicationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Team_RemoveApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Team_RemoveApplicationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public APIStatus Status {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIStatus)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void Team_ListCompletedEventHandler(object sender, Team_ListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Team_ListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Team_ListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public APIStatus Status {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIStatus)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public PlatformTeam[] PlatformTeams {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PlatformTeam[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void Team_AssignApplicationCompletedEventHandler(object sender, Team_AssignApplicationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Team_AssignApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Team_AssignApplicationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public APIStatus Status {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIStatus)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void Team_RemoveUserCompletedEventHandler(object sender, Team_RemoveUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Team_RemoveUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Team_RemoveUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public APIStatus Status {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIStatus)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void Team_AddUserCompletedEventHandler(object sender, Team_AddUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Team_AddUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Team_AddUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public APIStatus Status {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIStatus)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591