
package lifetime.environments;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * The Platform API for getting information about the environments managed by the platform.
 * To use this API you need to send an authentication argument with username/password, or use the AuthenticationService Web Service API to acquire a session token to send as argument.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EnvironmentManagementService", targetNamespace = "http://LifeTimeServices/EnvironmentManagementService/", wsdlLocation = "http://outsystemscloud/LifeTimeServices/EnvironmentManagementService.asmx?WSDL")
public class EnvironmentManagementService
    extends Service
{

    private final static URL ENVIRONMENTMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(lifetime.environments.EnvironmentManagementService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = lifetime.environments.EnvironmentManagementService.class.getResource(".");
            url = new URL(baseUrl, "http://outsystemscloud/LifeTimeServices/EnvironmentManagementService.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://outsystemscloud/LifeTimeServices/EnvironmentManagementService.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ENVIRONMENTMANAGEMENTSERVICE_WSDL_LOCATION = url;
    }

    public EnvironmentManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnvironmentManagementService() {
        super(ENVIRONMENTMANAGEMENTSERVICE_WSDL_LOCATION, new QName("http://LifeTimeServices/EnvironmentManagementService/", "EnvironmentManagementService"));
    }

    /**
     * 
     * @return
     *     returns EnvironmentManagementServiceSoap
     */
    @WebEndpoint(name = "EnvironmentManagementServiceSoap")
    public EnvironmentManagementServiceSoap getEnvironmentManagementServiceSoap() {
        return super.getPort(new QName("http://LifeTimeServices/EnvironmentManagementService/", "EnvironmentManagementServiceSoap"), EnvironmentManagementServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnvironmentManagementServiceSoap
     */
    @WebEndpoint(name = "EnvironmentManagementServiceSoap")
    public EnvironmentManagementServiceSoap getEnvironmentManagementServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://LifeTimeServices/EnvironmentManagementService/", "EnvironmentManagementServiceSoap"), EnvironmentManagementServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns EnvironmentManagementServiceSoap
     */
    @WebEndpoint(name = "EnvironmentManagementServiceSoap12")
    public EnvironmentManagementServiceSoap getEnvironmentManagementServiceSoap12() {
        return super.getPort(new QName("http://LifeTimeServices/EnvironmentManagementService/", "EnvironmentManagementServiceSoap12"), EnvironmentManagementServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnvironmentManagementServiceSoap
     */
    @WebEndpoint(name = "EnvironmentManagementServiceSoap12")
    public EnvironmentManagementServiceSoap getEnvironmentManagementServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://LifeTimeServices/EnvironmentManagementService/", "EnvironmentManagementServiceSoap12"), EnvironmentManagementServiceSoap.class, features);
    }

}
