
package lifetime.environments;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EnvironmentManagementServiceSoap", targetNamespace = "http://LifeTimeServices/EnvironmentManagementService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EnvironmentManagementServiceSoap {


    /**
     * Returns a list of environments with their information, such as name, version of the OutSystems Platform, and Application Server.
     * 
     * @param status
     * @param authentication
     * @param environments
     * @param success
     */
    @WebMethod(operationName = "Environment_List", action = "http://LifeTimeServices/EnvironmentManagementService/Environment_List")
    @RequestWrapper(localName = "Environment_List", targetNamespace = "http://www.outsystems.com", className = "lifetime.environments.EnvironmentList")
    @ResponseWrapper(localName = "Environment_ListResponse", targetNamespace = "http://www.outsystems.com", className = "lifetime.environments.EnvironmentListResponse")
    public void environmentList(
        @WebParam(name = "Authentication", targetNamespace = "http://www.outsystems.com")
        WebServiceSimpleAuthentication authentication,
        @WebParam(name = "Success", targetNamespace = "http://www.outsystems.com", mode = WebParam.Mode.OUT)
        Holder<Boolean> success,
        @WebParam(name = "Status", targetNamespace = "http://www.outsystems.com", mode = WebParam.Mode.OUT)
        Holder<APIStatus> status,
        @WebParam(name = "Environments", targetNamespace = "http://www.outsystems.com", mode = WebParam.Mode.OUT)
        Holder<ArrayOfEnvironmentInfo> environments);

    /**
     * The list of permission levels that a platform user has over an environment.
     * 
     * @param status
     * @param authentication
     * @param success
     * @param rolePermissionLevels
     */
    @WebMethod(operationName = "EnvironmentPermissionLevel_List", action = "http://LifeTimeServices/EnvironmentManagementService/EnvironmentPermissionLevel_List")
    @RequestWrapper(localName = "EnvironmentPermissionLevel_List", targetNamespace = "http://www.outsystems.com", className = "lifetime.environments.EnvironmentPermissionLevelList")
    @ResponseWrapper(localName = "EnvironmentPermissionLevel_ListResponse", targetNamespace = "http://www.outsystems.com", className = "lifetime.environments.EnvironmentPermissionLevelListResponse")
    public void environmentPermissionLevelList(
        @WebParam(name = "Authentication", targetNamespace = "http://www.outsystems.com")
        WebServiceSimpleAuthentication authentication,
        @WebParam(name = "Success", targetNamespace = "http://www.outsystems.com", mode = WebParam.Mode.OUT)
        Holder<Boolean> success,
        @WebParam(name = "Status", targetNamespace = "http://www.outsystems.com", mode = WebParam.Mode.OUT)
        Holder<APIStatus> status,
        @WebParam(name = "RolePermissionLevels", targetNamespace = "http://www.outsystems.com", mode = WebParam.Mode.OUT)
        Holder<ArrayOfEnvironmentPermissionLevel> rolePermissionLevels);

}
