//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace LifetimeIntegration.LifetimeEnvironments {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EnvironmentManagementServiceSoap", Namespace="http://LifeTimeServices/EnvironmentManagementService/")]
    public partial class EnvironmentManagementService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Environment_ListOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnvironmentPermissionLevel_ListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EnvironmentManagementService() {
            this.Url = global::LifetimeIntegration.Properties.Settings.Default.LifetimeIntegration_LifetimeEnvironments_EnvironmentManagementService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Environment_ListCompletedEventHandler Environment_ListCompleted;
        
        /// <remarks/>
        public event EnvironmentPermissionLevel_ListCompletedEventHandler EnvironmentPermissionLevel_ListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LifeTimeServices/EnvironmentManagementService/Environment_List", RequestNamespace="http://www.outsystems.com", ResponseNamespace="http://www.outsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("Environments")]
        public EnvironmentInfo[] Environment_List(WebServiceSimpleAuthentication Authentication, out APIStatus Status, out bool Success) {
            object[] results = this.Invoke("Environment_List", new object[] {
                        Authentication});
            Status = ((APIStatus)(results[1]));
            Success = ((bool)(results[2]));
            return ((EnvironmentInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void Environment_ListAsync(WebServiceSimpleAuthentication Authentication) {
            this.Environment_ListAsync(Authentication, null);
        }
        
        /// <remarks/>
        public void Environment_ListAsync(WebServiceSimpleAuthentication Authentication, object userState) {
            if ((this.Environment_ListOperationCompleted == null)) {
                this.Environment_ListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnvironment_ListOperationCompleted);
            }
            this.InvokeAsync("Environment_List", new object[] {
                        Authentication}, this.Environment_ListOperationCompleted, userState);
        }
        
        private void OnEnvironment_ListOperationCompleted(object arg) {
            if ((this.Environment_ListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Environment_ListCompleted(this, new Environment_ListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LifeTimeServices/EnvironmentManagementService/EnvironmentPermissionLevel_L" +
            "ist", RequestNamespace="http://www.outsystems.com", ResponseNamespace="http://www.outsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("RolePermissionLevels")]
        public EnvironmentPermissionLevel[] EnvironmentPermissionLevel_List(WebServiceSimpleAuthentication Authentication, out APIStatus Status, out bool Success) {
            object[] results = this.Invoke("EnvironmentPermissionLevel_List", new object[] {
                        Authentication});
            Status = ((APIStatus)(results[1]));
            Success = ((bool)(results[2]));
            return ((EnvironmentPermissionLevel[])(results[0]));
        }
        
        /// <remarks/>
        public void EnvironmentPermissionLevel_ListAsync(WebServiceSimpleAuthentication Authentication) {
            this.EnvironmentPermissionLevel_ListAsync(Authentication, null);
        }
        
        /// <remarks/>
        public void EnvironmentPermissionLevel_ListAsync(WebServiceSimpleAuthentication Authentication, object userState) {
            if ((this.EnvironmentPermissionLevel_ListOperationCompleted == null)) {
                this.EnvironmentPermissionLevel_ListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnvironmentPermissionLevel_ListOperationCompleted);
            }
            this.InvokeAsync("EnvironmentPermissionLevel_List", new object[] {
                        Authentication}, this.EnvironmentPermissionLevel_ListOperationCompleted, userState);
        }
        
        private void OnEnvironmentPermissionLevel_ListOperationCompleted(object arg) {
            if ((this.EnvironmentPermissionLevel_ListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnvironmentPermissionLevel_ListCompleted(this, new EnvironmentPermissionLevel_ListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.outsystems.com")]
    public partial class WebServiceSimpleAuthentication {
        
        private string usernameField;
        
        private string passwordField;
        
        private string tokenField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.outsystems.com")]
    public partial class EnvironmentPermissionLevel {
        
        private int idField;
        
        private string labelField;
        
        private string shortLabelField;
        
        private string descriptionField;
        
        private int levelField;
        
        private int applicationLevelIdField;
        
        private bool isReadOnlyField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        public string ShortLabel {
            get {
                return this.shortLabelField;
            }
            set {
                this.shortLabelField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        public int ApplicationLevelId {
            get {
                return this.applicationLevelIdField;
            }
            set {
                this.applicationLevelIdField = value;
            }
        }
        
        /// <remarks/>
        public bool IsReadOnly {
            get {
                return this.isReadOnlyField;
            }
            set {
                this.isReadOnlyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.outsystems.com")]
    public partial class APIStatus {
        
        private int idField;
        
        private int responseIdField;
        
        private string responseMessageField;
        
        private string responseAdditionalInfoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ResponseId {
            get {
                return this.responseIdField;
            }
            set {
                this.responseIdField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseAdditionalInfo {
            get {
                return this.responseAdditionalInfoField;
            }
            set {
                this.responseAdditionalInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.outsystems.com")]
    public partial class EnvironmentInfo {
        
        private string keyField;
        
        private string nameField;
        
        private string versionField;
        
        private int orderField;
        
        private string hostNameField;
        
        private bool useHTTPSField;
        
        private bool inProductionModeField;
        
        private int numberOfFrontEndsField;
        
        private string applicationServerTypeField;
        
        private string applicationServerField;
        
        private string databaseProviderField;
        
        private bool isCloudEnvironmentField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        public string HostName {
            get {
                return this.hostNameField;
            }
            set {
                this.hostNameField = value;
            }
        }
        
        /// <remarks/>
        public bool UseHTTPS {
            get {
                return this.useHTTPSField;
            }
            set {
                this.useHTTPSField = value;
            }
        }
        
        /// <remarks/>
        public bool InProductionMode {
            get {
                return this.inProductionModeField;
            }
            set {
                this.inProductionModeField = value;
            }
        }
        
        /// <remarks/>
        public int NumberOfFrontEnds {
            get {
                return this.numberOfFrontEndsField;
            }
            set {
                this.numberOfFrontEndsField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationServerType {
            get {
                return this.applicationServerTypeField;
            }
            set {
                this.applicationServerTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationServer {
            get {
                return this.applicationServerField;
            }
            set {
                this.applicationServerField = value;
            }
        }
        
        /// <remarks/>
        public string DatabaseProvider {
            get {
                return this.databaseProviderField;
            }
            set {
                this.databaseProviderField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCloudEnvironment {
            get {
                return this.isCloudEnvironmentField;
            }
            set {
                this.isCloudEnvironmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void Environment_ListCompletedEventHandler(object sender, Environment_ListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Environment_ListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Environment_ListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EnvironmentInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EnvironmentInfo[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public APIStatus Status {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIStatus)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void EnvironmentPermissionLevel_ListCompletedEventHandler(object sender, EnvironmentPermissionLevel_ListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnvironmentPermissionLevel_ListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnvironmentPermissionLevel_ListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EnvironmentPermissionLevel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EnvironmentPermissionLevel[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public APIStatus Status {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIStatus)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591