//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace LifetimeIntegration.LifetimeUsers {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UserManagementServiceSoap", Namespace="http://LifeTimeServices/UserManagementService/")]
    public partial class UserManagementService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback User_ChangePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback User_DeleteApplicationPermissionOperationCompleted;
        
        private System.Threading.SendOrPostCallback User_GetAllPermissionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback User_UpdateApplicationPermissionOperationCompleted;
        
        private System.Threading.SendOrPostCallback User_SetApplicationRoleOperationCompleted;
        
        private System.Threading.SendOrPostCallback User_SetInactiveOperationCompleted;
        
        private System.Threading.SendOrPostCallback User_GetApplicationPermissionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback User_SetActiveOperationCompleted;
        
        private System.Threading.SendOrPostCallback User_CreateOrUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback User_ChangeUsernameOperationCompleted;
        
        private System.Threading.SendOrPostCallback User_ListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UserManagementService() {
            this.Url = global::LifetimeIntegration.Properties.Settings.Default.LifetimeIntegration_LifetimeUsers_UserManagementService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event User_ChangePasswordCompletedEventHandler User_ChangePasswordCompleted;
        
        /// <remarks/>
        public event User_DeleteApplicationPermissionCompletedEventHandler User_DeleteApplicationPermissionCompleted;
        
        /// <remarks/>
        public event User_GetAllPermissionsCompletedEventHandler User_GetAllPermissionsCompleted;
        
        /// <remarks/>
        public event User_UpdateApplicationPermissionCompletedEventHandler User_UpdateApplicationPermissionCompleted;
        
        /// <remarks/>
        public event User_SetApplicationRoleCompletedEventHandler User_SetApplicationRoleCompleted;
        
        /// <remarks/>
        public event User_SetInactiveCompletedEventHandler User_SetInactiveCompleted;
        
        /// <remarks/>
        public event User_GetApplicationPermissionsCompletedEventHandler User_GetApplicationPermissionsCompleted;
        
        /// <remarks/>
        public event User_SetActiveCompletedEventHandler User_SetActiveCompleted;
        
        /// <remarks/>
        public event User_CreateOrUpdateCompletedEventHandler User_CreateOrUpdateCompleted;
        
        /// <remarks/>
        public event User_ChangeUsernameCompletedEventHandler User_ChangeUsernameCompleted;
        
        /// <remarks/>
        public event User_ListCompletedEventHandler User_ListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LifeTimeServices/UserManagementService/User_ChangePassword", RequestNamespace="http://www.outsystems.com", ResponseNamespace="http://www.outsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Status")]
        public APIStatus User_ChangePassword(WebServiceSimpleAuthentication Authentication, string Username, string NewPassword, bool EncryptPassword, out bool Success) {
            object[] results = this.Invoke("User_ChangePassword", new object[] {
                        Authentication,
                        Username,
                        NewPassword,
                        EncryptPassword});
            Success = ((bool)(results[1]));
            return ((APIStatus)(results[0]));
        }
        
        /// <remarks/>
        public void User_ChangePasswordAsync(WebServiceSimpleAuthentication Authentication, string Username, string NewPassword, bool EncryptPassword) {
            this.User_ChangePasswordAsync(Authentication, Username, NewPassword, EncryptPassword, null);
        }
        
        /// <remarks/>
        public void User_ChangePasswordAsync(WebServiceSimpleAuthentication Authentication, string Username, string NewPassword, bool EncryptPassword, object userState) {
            if ((this.User_ChangePasswordOperationCompleted == null)) {
                this.User_ChangePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_ChangePasswordOperationCompleted);
            }
            this.InvokeAsync("User_ChangePassword", new object[] {
                        Authentication,
                        Username,
                        NewPassword,
                        EncryptPassword}, this.User_ChangePasswordOperationCompleted, userState);
        }
        
        private void OnUser_ChangePasswordOperationCompleted(object arg) {
            if ((this.User_ChangePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_ChangePasswordCompleted(this, new User_ChangePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LifeTimeServices/UserManagementService/User_DeleteApplicationPermission", RequestNamespace="http://www.outsystems.com", ResponseNamespace="http://www.outsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Status")]
        public APIStatus User_DeleteApplicationPermission(WebServiceSimpleAuthentication Authentication, string Username, string ApplicationKey, out bool Success) {
            object[] results = this.Invoke("User_DeleteApplicationPermission", new object[] {
                        Authentication,
                        Username,
                        ApplicationKey});
            Success = ((bool)(results[1]));
            return ((APIStatus)(results[0]));
        }
        
        /// <remarks/>
        public void User_DeleteApplicationPermissionAsync(WebServiceSimpleAuthentication Authentication, string Username, string ApplicationKey) {
            this.User_DeleteApplicationPermissionAsync(Authentication, Username, ApplicationKey, null);
        }
        
        /// <remarks/>
        public void User_DeleteApplicationPermissionAsync(WebServiceSimpleAuthentication Authentication, string Username, string ApplicationKey, object userState) {
            if ((this.User_DeleteApplicationPermissionOperationCompleted == null)) {
                this.User_DeleteApplicationPermissionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_DeleteApplicationPermissionOperationCompleted);
            }
            this.InvokeAsync("User_DeleteApplicationPermission", new object[] {
                        Authentication,
                        Username,
                        ApplicationKey}, this.User_DeleteApplicationPermissionOperationCompleted, userState);
        }
        
        private void OnUser_DeleteApplicationPermissionOperationCompleted(object arg) {
            if ((this.User_DeleteApplicationPermissionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_DeleteApplicationPermissionCompleted(this, new User_DeleteApplicationPermissionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LifeTimeServices/UserManagementService/User_GetAllPermissions", RequestNamespace="http://www.outsystems.com", ResponseNamespace="http://www.outsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ApplicationPermissions")]
        public WORCApplicationShortInfoApplicationPermissionsRecord[] User_GetAllPermissions(WebServiceSimpleAuthentication Authentication, string Username, out ApplicationPermissions PlatformRolePermissions, out APIStatus Status, out bool Success) {
            object[] results = this.Invoke("User_GetAllPermissions", new object[] {
                        Authentication,
                        Username});
            PlatformRolePermissions = ((ApplicationPermissions)(results[1]));
            Status = ((APIStatus)(results[2]));
            Success = ((bool)(results[3]));
            return ((WORCApplicationShortInfoApplicationPermissionsRecord[])(results[0]));
        }
        
        /// <remarks/>
        public void User_GetAllPermissionsAsync(WebServiceSimpleAuthentication Authentication, string Username) {
            this.User_GetAllPermissionsAsync(Authentication, Username, null);
        }
        
        /// <remarks/>
        public void User_GetAllPermissionsAsync(WebServiceSimpleAuthentication Authentication, string Username, object userState) {
            if ((this.User_GetAllPermissionsOperationCompleted == null)) {
                this.User_GetAllPermissionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_GetAllPermissionsOperationCompleted);
            }
            this.InvokeAsync("User_GetAllPermissions", new object[] {
                        Authentication,
                        Username}, this.User_GetAllPermissionsOperationCompleted, userState);
        }
        
        private void OnUser_GetAllPermissionsOperationCompleted(object arg) {
            if ((this.User_GetAllPermissionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_GetAllPermissionsCompleted(this, new User_GetAllPermissionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LifeTimeServices/UserManagementService/User_UpdateApplicationPermission", RequestNamespace="http://www.outsystems.com", ResponseNamespace="http://www.outsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Status")]
        public APIStatus User_UpdateApplicationPermission(WebServiceSimpleAuthentication Authentication, string Username, string ApplicationKey, string EnvironmentKey, int PermissionLevelId, out bool Success) {
            object[] results = this.Invoke("User_UpdateApplicationPermission", new object[] {
                        Authentication,
                        Username,
                        ApplicationKey,
                        EnvironmentKey,
                        PermissionLevelId});
            Success = ((bool)(results[1]));
            return ((APIStatus)(results[0]));
        }
        
        /// <remarks/>
        public void User_UpdateApplicationPermissionAsync(WebServiceSimpleAuthentication Authentication, string Username, string ApplicationKey, string EnvironmentKey, int PermissionLevelId) {
            this.User_UpdateApplicationPermissionAsync(Authentication, Username, ApplicationKey, EnvironmentKey, PermissionLevelId, null);
        }
        
        /// <remarks/>
        public void User_UpdateApplicationPermissionAsync(WebServiceSimpleAuthentication Authentication, string Username, string ApplicationKey, string EnvironmentKey, int PermissionLevelId, object userState) {
            if ((this.User_UpdateApplicationPermissionOperationCompleted == null)) {
                this.User_UpdateApplicationPermissionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_UpdateApplicationPermissionOperationCompleted);
            }
            this.InvokeAsync("User_UpdateApplicationPermission", new object[] {
                        Authentication,
                        Username,
                        ApplicationKey,
                        EnvironmentKey,
                        PermissionLevelId}, this.User_UpdateApplicationPermissionOperationCompleted, userState);
        }
        
        private void OnUser_UpdateApplicationPermissionOperationCompleted(object arg) {
            if ((this.User_UpdateApplicationPermissionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_UpdateApplicationPermissionCompleted(this, new User_UpdateApplicationPermissionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LifeTimeServices/UserManagementService/User_SetApplicationRole", RequestNamespace="http://www.outsystems.com", ResponseNamespace="http://www.outsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Status")]
        public APIStatus User_SetApplicationRole(WebServiceSimpleAuthentication Authentication, string Username, string ApplicationKey, string RoleName, out bool Success) {
            object[] results = this.Invoke("User_SetApplicationRole", new object[] {
                        Authentication,
                        Username,
                        ApplicationKey,
                        RoleName});
            Success = ((bool)(results[1]));
            return ((APIStatus)(results[0]));
        }
        
        /// <remarks/>
        public void User_SetApplicationRoleAsync(WebServiceSimpleAuthentication Authentication, string Username, string ApplicationKey, string RoleName) {
            this.User_SetApplicationRoleAsync(Authentication, Username, ApplicationKey, RoleName, null);
        }
        
        /// <remarks/>
        public void User_SetApplicationRoleAsync(WebServiceSimpleAuthentication Authentication, string Username, string ApplicationKey, string RoleName, object userState) {
            if ((this.User_SetApplicationRoleOperationCompleted == null)) {
                this.User_SetApplicationRoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_SetApplicationRoleOperationCompleted);
            }
            this.InvokeAsync("User_SetApplicationRole", new object[] {
                        Authentication,
                        Username,
                        ApplicationKey,
                        RoleName}, this.User_SetApplicationRoleOperationCompleted, userState);
        }
        
        private void OnUser_SetApplicationRoleOperationCompleted(object arg) {
            if ((this.User_SetApplicationRoleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_SetApplicationRoleCompleted(this, new User_SetApplicationRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LifeTimeServices/UserManagementService/User_SetInactive", RequestNamespace="http://www.outsystems.com", ResponseNamespace="http://www.outsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Status")]
        public APIStatus User_SetInactive(WebServiceSimpleAuthentication Authentication, string Username, out bool Success) {
            object[] results = this.Invoke("User_SetInactive", new object[] {
                        Authentication,
                        Username});
            Success = ((bool)(results[1]));
            return ((APIStatus)(results[0]));
        }
        
        /// <remarks/>
        public void User_SetInactiveAsync(WebServiceSimpleAuthentication Authentication, string Username) {
            this.User_SetInactiveAsync(Authentication, Username, null);
        }
        
        /// <remarks/>
        public void User_SetInactiveAsync(WebServiceSimpleAuthentication Authentication, string Username, object userState) {
            if ((this.User_SetInactiveOperationCompleted == null)) {
                this.User_SetInactiveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_SetInactiveOperationCompleted);
            }
            this.InvokeAsync("User_SetInactive", new object[] {
                        Authentication,
                        Username}, this.User_SetInactiveOperationCompleted, userState);
        }
        
        private void OnUser_SetInactiveOperationCompleted(object arg) {
            if ((this.User_SetInactiveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_SetInactiveCompleted(this, new User_SetInactiveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LifeTimeServices/UserManagementService/User_GetApplicationPermissions", RequestNamespace="http://www.outsystems.com", ResponseNamespace="http://www.outsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ArePlatformRolePermissions")]
        public bool User_GetApplicationPermissions(WebServiceSimpleAuthentication Authentication, string Username, string ApplicationKey, out ApplicationPermissions ApplicationPermissions, out APIStatus Status, out bool Success) {
            object[] results = this.Invoke("User_GetApplicationPermissions", new object[] {
                        Authentication,
                        Username,
                        ApplicationKey});
            ApplicationPermissions = ((ApplicationPermissions)(results[1]));
            Status = ((APIStatus)(results[2]));
            Success = ((bool)(results[3]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void User_GetApplicationPermissionsAsync(WebServiceSimpleAuthentication Authentication, string Username, string ApplicationKey) {
            this.User_GetApplicationPermissionsAsync(Authentication, Username, ApplicationKey, null);
        }
        
        /// <remarks/>
        public void User_GetApplicationPermissionsAsync(WebServiceSimpleAuthentication Authentication, string Username, string ApplicationKey, object userState) {
            if ((this.User_GetApplicationPermissionsOperationCompleted == null)) {
                this.User_GetApplicationPermissionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_GetApplicationPermissionsOperationCompleted);
            }
            this.InvokeAsync("User_GetApplicationPermissions", new object[] {
                        Authentication,
                        Username,
                        ApplicationKey}, this.User_GetApplicationPermissionsOperationCompleted, userState);
        }
        
        private void OnUser_GetApplicationPermissionsOperationCompleted(object arg) {
            if ((this.User_GetApplicationPermissionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_GetApplicationPermissionsCompleted(this, new User_GetApplicationPermissionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LifeTimeServices/UserManagementService/User_SetActive", RequestNamespace="http://www.outsystems.com", ResponseNamespace="http://www.outsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Status")]
        public APIStatus User_SetActive(WebServiceSimpleAuthentication Authentication, string Username, out bool Success) {
            object[] results = this.Invoke("User_SetActive", new object[] {
                        Authentication,
                        Username});
            Success = ((bool)(results[1]));
            return ((APIStatus)(results[0]));
        }
        
        /// <remarks/>
        public void User_SetActiveAsync(WebServiceSimpleAuthentication Authentication, string Username) {
            this.User_SetActiveAsync(Authentication, Username, null);
        }
        
        /// <remarks/>
        public void User_SetActiveAsync(WebServiceSimpleAuthentication Authentication, string Username, object userState) {
            if ((this.User_SetActiveOperationCompleted == null)) {
                this.User_SetActiveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_SetActiveOperationCompleted);
            }
            this.InvokeAsync("User_SetActive", new object[] {
                        Authentication,
                        Username}, this.User_SetActiveOperationCompleted, userState);
        }
        
        private void OnUser_SetActiveOperationCompleted(object arg) {
            if ((this.User_SetActiveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_SetActiveCompleted(this, new User_SetActiveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LifeTimeServices/UserManagementService/User_CreateOrUpdate", RequestNamespace="http://www.outsystems.com", ResponseNamespace="http://www.outsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("PlatformUser")]
        public PlatformUser User_CreateOrUpdate(WebServiceSimpleAuthentication Authentication, string Username, string Password, bool EncryptPassword, string Name, string Email, string RoleName, out APIStatus Status, out bool Success) {
            object[] results = this.Invoke("User_CreateOrUpdate", new object[] {
                        Authentication,
                        Username,
                        Password,
                        EncryptPassword,
                        Name,
                        Email,
                        RoleName});
            Status = ((APIStatus)(results[1]));
            Success = ((bool)(results[2]));
            return ((PlatformUser)(results[0]));
        }
        
        /// <remarks/>
        public void User_CreateOrUpdateAsync(WebServiceSimpleAuthentication Authentication, string Username, string Password, bool EncryptPassword, string Name, string Email, string RoleName) {
            this.User_CreateOrUpdateAsync(Authentication, Username, Password, EncryptPassword, Name, Email, RoleName, null);
        }
        
        /// <remarks/>
        public void User_CreateOrUpdateAsync(WebServiceSimpleAuthentication Authentication, string Username, string Password, bool EncryptPassword, string Name, string Email, string RoleName, object userState) {
            if ((this.User_CreateOrUpdateOperationCompleted == null)) {
                this.User_CreateOrUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_CreateOrUpdateOperationCompleted);
            }
            this.InvokeAsync("User_CreateOrUpdate", new object[] {
                        Authentication,
                        Username,
                        Password,
                        EncryptPassword,
                        Name,
                        Email,
                        RoleName}, this.User_CreateOrUpdateOperationCompleted, userState);
        }
        
        private void OnUser_CreateOrUpdateOperationCompleted(object arg) {
            if ((this.User_CreateOrUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_CreateOrUpdateCompleted(this, new User_CreateOrUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LifeTimeServices/UserManagementService/User_ChangeUsername", RequestNamespace="http://www.outsystems.com", ResponseNamespace="http://www.outsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Status")]
        public APIStatus User_ChangeUsername(WebServiceSimpleAuthentication Authentication, string OldUsername, string NewUsername, out bool Success) {
            object[] results = this.Invoke("User_ChangeUsername", new object[] {
                        Authentication,
                        OldUsername,
                        NewUsername});
            Success = ((bool)(results[1]));
            return ((APIStatus)(results[0]));
        }
        
        /// <remarks/>
        public void User_ChangeUsernameAsync(WebServiceSimpleAuthentication Authentication, string OldUsername, string NewUsername) {
            this.User_ChangeUsernameAsync(Authentication, OldUsername, NewUsername, null);
        }
        
        /// <remarks/>
        public void User_ChangeUsernameAsync(WebServiceSimpleAuthentication Authentication, string OldUsername, string NewUsername, object userState) {
            if ((this.User_ChangeUsernameOperationCompleted == null)) {
                this.User_ChangeUsernameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_ChangeUsernameOperationCompleted);
            }
            this.InvokeAsync("User_ChangeUsername", new object[] {
                        Authentication,
                        OldUsername,
                        NewUsername}, this.User_ChangeUsernameOperationCompleted, userState);
        }
        
        private void OnUser_ChangeUsernameOperationCompleted(object arg) {
            if ((this.User_ChangeUsernameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_ChangeUsernameCompleted(this, new User_ChangeUsernameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LifeTimeServices/UserManagementService/User_List", RequestNamespace="http://www.outsystems.com", ResponseNamespace="http://www.outsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("PlatformUsers")]
        public PlatformUser[] User_List(WebServiceSimpleAuthentication Authentication, bool ShowInactive, out APIStatus Status, out bool Success) {
            object[] results = this.Invoke("User_List", new object[] {
                        Authentication,
                        ShowInactive});
            Status = ((APIStatus)(results[1]));
            Success = ((bool)(results[2]));
            return ((PlatformUser[])(results[0]));
        }
        
        /// <remarks/>
        public void User_ListAsync(WebServiceSimpleAuthentication Authentication, bool ShowInactive) {
            this.User_ListAsync(Authentication, ShowInactive, null);
        }
        
        /// <remarks/>
        public void User_ListAsync(WebServiceSimpleAuthentication Authentication, bool ShowInactive, object userState) {
            if ((this.User_ListOperationCompleted == null)) {
                this.User_ListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_ListOperationCompleted);
            }
            this.InvokeAsync("User_List", new object[] {
                        Authentication,
                        ShowInactive}, this.User_ListOperationCompleted, userState);
        }
        
        private void OnUser_ListOperationCompleted(object arg) {
            if ((this.User_ListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_ListCompleted(this, new User_ListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.outsystems.com")]
    public partial class WebServiceSimpleAuthentication {
        
        private string usernameField;
        
        private string passwordField;
        
        private string tokenField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.outsystems.com")]
    public partial class PlatformUser {
        
        private int idField;
        
        private string usernameField;
        
        private string nameField;
        
        private string emailField;
        
        private string roleNameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string RoleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.outsystems.com")]
    public partial class EnvironmentPermissionForApplication {
        
        private string environmentKeyField;
        
        private string environmentNameField;
        
        private string environmentHostField;
        
        private string environmentTypeField;
        
        private int applicationPermissionLevelIdField;
        
        /// <remarks/>
        public string EnvironmentKey {
            get {
                return this.environmentKeyField;
            }
            set {
                this.environmentKeyField = value;
            }
        }
        
        /// <remarks/>
        public string EnvironmentName {
            get {
                return this.environmentNameField;
            }
            set {
                this.environmentNameField = value;
            }
        }
        
        /// <remarks/>
        public string EnvironmentHost {
            get {
                return this.environmentHostField;
            }
            set {
                this.environmentHostField = value;
            }
        }
        
        /// <remarks/>
        public string EnvironmentType {
            get {
                return this.environmentTypeField;
            }
            set {
                this.environmentTypeField = value;
            }
        }
        
        /// <remarks/>
        public int ApplicationPermissionLevelId {
            get {
                return this.applicationPermissionLevelIdField;
            }
            set {
                this.applicationPermissionLevelIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.outsystems.com")]
    public partial class ApplicationPermissions {
        
        private EnvironmentPermissionForApplication[] applicationPermissions1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("ApplicationPermissions")]
        public EnvironmentPermissionForApplication[] ApplicationPermissions1 {
            get {
                return this.applicationPermissions1Field;
            }
            set {
                this.applicationPermissions1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.outsystems.com")]
    public partial class ApplicationShortInfo {
        
        private string nameField;
        
        private string keyField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.outsystems.com")]
    public partial class WORCApplicationShortInfoApplicationPermissionsRecord {
        
        private ApplicationShortInfo ssSTApplicationShortInfoField;
        
        private ApplicationPermissions ssSTApplicationPermissionsField;
        
        /// <remarks/>
        public ApplicationShortInfo ssSTApplicationShortInfo {
            get {
                return this.ssSTApplicationShortInfoField;
            }
            set {
                this.ssSTApplicationShortInfoField = value;
            }
        }
        
        /// <remarks/>
        public ApplicationPermissions ssSTApplicationPermissions {
            get {
                return this.ssSTApplicationPermissionsField;
            }
            set {
                this.ssSTApplicationPermissionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.outsystems.com")]
    public partial class APIStatus {
        
        private int idField;
        
        private int responseIdField;
        
        private string responseMessageField;
        
        private string responseAdditionalInfoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ResponseId {
            get {
                return this.responseIdField;
            }
            set {
                this.responseIdField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseAdditionalInfo {
            get {
                return this.responseAdditionalInfoField;
            }
            set {
                this.responseAdditionalInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void User_ChangePasswordCompletedEventHandler(object sender, User_ChangePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_ChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_ChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public APIStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIStatus)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void User_DeleteApplicationPermissionCompletedEventHandler(object sender, User_DeleteApplicationPermissionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_DeleteApplicationPermissionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_DeleteApplicationPermissionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public APIStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIStatus)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void User_GetAllPermissionsCompletedEventHandler(object sender, User_GetAllPermissionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_GetAllPermissionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_GetAllPermissionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WORCApplicationShortInfoApplicationPermissionsRecord[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WORCApplicationShortInfoApplicationPermissionsRecord[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ApplicationPermissions PlatformRolePermissions {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApplicationPermissions)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public APIStatus Status {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIStatus)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void User_UpdateApplicationPermissionCompletedEventHandler(object sender, User_UpdateApplicationPermissionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_UpdateApplicationPermissionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_UpdateApplicationPermissionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public APIStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIStatus)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void User_SetApplicationRoleCompletedEventHandler(object sender, User_SetApplicationRoleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_SetApplicationRoleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_SetApplicationRoleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public APIStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIStatus)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void User_SetInactiveCompletedEventHandler(object sender, User_SetInactiveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_SetInactiveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_SetInactiveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public APIStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIStatus)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void User_GetApplicationPermissionsCompletedEventHandler(object sender, User_GetApplicationPermissionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_GetApplicationPermissionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_GetApplicationPermissionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ApplicationPermissions ApplicationPermissions {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApplicationPermissions)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public APIStatus Status {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIStatus)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void User_SetActiveCompletedEventHandler(object sender, User_SetActiveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_SetActiveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_SetActiveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public APIStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIStatus)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void User_CreateOrUpdateCompletedEventHandler(object sender, User_CreateOrUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_CreateOrUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_CreateOrUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PlatformUser Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PlatformUser)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public APIStatus Status {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIStatus)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void User_ChangeUsernameCompletedEventHandler(object sender, User_ChangeUsernameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_ChangeUsernameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_ChangeUsernameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public APIStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIStatus)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void User_ListCompletedEventHandler(object sender, User_ListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_ListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_ListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PlatformUser[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PlatformUser[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public APIStatus Status {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIStatus)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591